#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.nvm/nvm.sh
nvm use v0.10.32


# added by travis gem
[ -f /Users/minodisk/.travis/travis.sh ] && source /Users/minodisk/.travis/travis.sh
